version: "3.3"

services: 
  app:
    container_name: restoneranfitrion_app_servicio_inventario
    restart: always 
    build: .
    networks:
      - backend
    ports:
      - "7500:6500"
    links:
      - postgres
  postgres:
    container_name: postgres_db
    restart: always
    image: "postgres:13"
    networks:
      - backend
    ports:
      - "7000:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgresxd2
      - POSTGRES_PASSWORD=postgresxd2
      - POSTGRES_DB=postgresxd2
  pgadmin:
    restart: always
    image: "dpage/pgadmin4"
    networks:
      - backend
    ports:
      - "90:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: adminxd2@adminxd2.com
      PGADMIN_DEFAULT_PASSWORD: adminxd2
    depends_on:
      - postgres
  mongo:
    image: mongo
    restart: always
    networks:
      - backend
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbbusiness_user
      MONGO_INITDB_ROOT_PASSWORD: mon9h9065g
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8452:8081"
    networks:
      - backend
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongobusiness_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodbssqs
      ME_CONFIG_MONGODB_URL: mongodb://mongodbbusiness_user:mon9h9065g@mongo:27017/

networks:
  backend:
    driver: bridge
    ipam: 
      driver: default 








