version: "3.3"

services: 
  app:
    container_name: restoneranfitrion_app_servicio_inventario
    restart: always 
    build: .
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
    networks:
      - backend
    ports:
      - "7500:6500"
    links:
      - postgres
      - redis
  redis:
    container_name: redis_db
    restart: always
    image: "redis:6.0.16"
    networks:
      - backend
    ports: 
      - "6000:6379"
  postgres:
    container_name: postgres_db
    restart: always
    image: "postgres:13"
    networks:
      - backend
    ports:
      - "7000:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgresxd2
      - POSTGRES_PASSWORD=asf45vcf235sfds435GFHg435fd3h2s
      - POSTGRES_DB=postgresxd2
  pgadmin:
    restart: always
    image: "dpage/pgadmin4"
    networks:
      - backend
    ports:
      - "90:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: adminxd2@adminxd2.com
      PGADMIN_DEFAULT_PASSWORD: asf435vcf235HEFGHg435fd3h2s
    depends_on:
      - postgres
  mongo:
    image: mongo
    restart: always
    networks:
      - backend
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbinventorydata
      MONGO_INITDB_ROOT_PASSWORD: mongo412ddb1r2
  mongo-express:
    image: "mongo-express:1.0.0-alpha.4"
    restart: always
    ports:
      - "91:8081"
    networks:
      - backend
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongodbinventorydata
      ME_CONFIG_MONGODB_ADMINPASSWORD: adgadsfg234GWe5Ggwf34G52fag3
      ME_CONFIG_BASICAUTH_USERNAME: mongobasicauthfw26666
      ME_CONFIG_BASICAUTH_PASSWORD: dasd23GG3321Fa435fuj6c
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_MONGODB_URL: mongodb://mongodbinventorydata:mongo412ddb1r2@mongo:27017/
  traefik: # apache.app.test - nginx.app.test
    image: traefik:v2.3.6
    labels: 
      - "traefik.http.routers.api.rule=Host(`localhost`)"
    ports: 
      - 100:80
      - 9004:8080
      - 443:443
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json

networks:
  backend:
    driver: bridge
    ipam: 
      driver: default 








