version: "3.3"

services: 
  a-inventario-carta:
    restart: always 
    build: .
    labels: 
      - "traefik.http.routers.a-inventario-carta.rule=Host(`a-inventario-carta.restoner-api.fun`)"
    networks:
      - backend
    links:
      - postgres-master
      - redis
      - postgresql-slave
  redis:
    container_name: redis_db
    restart: always
    image: "redis:6.0.16"
    networks:
      - backend
    volumes: 
      - cache:/data
    ports: 
      - "6000:6379"
  postgres-master:
    container_name: postgres_db
    restart: always
    image: "bitnami/postgresql:14.4.0"
    networks:
      - backend
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    ports:
      - "5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - DATABASE_HOST=127.0.0.1
      - POSTGRESQL_REPLICATION_USER=replicacion_usuario_123
      - POSTGRESQL_REPLICATION_PASSWORD=replicacion_contrasenia_123
      - POSTGRESQL_USERNAME=postgresxd2
      - POSTGRESQL_PASSWORD=asf45vcf235sfds435GFHg435fd3h2s
      - POSTGRESQL_DATABASE=postgresxd2
  postgresql-slave:
    image: 'bitnami/postgresql:14.4.0'
    ports:
      - "6432:5432"
    networks:
      - backend
    depends_on:
      - postgres-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicacion_usuario_123
      - POSTGRESQL_REPLICATION_PASSWORD=replicacion_contrasenia_123
      - POSTGRESQL_MASTER_HOST=postgres-master
      - POSTGRESQL_PASSWORD=asf45vcf235sfds435GFHg435fd3h2s
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
  pgadmin:
    restart: always
    image: "dpage/pgadmin4"
    networks:
      - backend
    ports:
      - "90:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: adminxd2@adminxd2.com
      PGADMIN_DEFAULT_PASSWORD: asf435vcf235HEFGHg435fd3h2s
    depends_on:
      - postgres-master
  mongo:
    image: mongo
    restart: always
    networks:
      - backend
    ports:
      - "27017:27017"
    volumes: 
      - shared_database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbinventorydata
      MONGO_INITDB_ROOT_PASSWORD: mongo412ddb1r2
  mongo-express:
    image: "mongo-express:1.0.0-alpha.4"
    restart: always
    ports:
      - "91:8081"
    networks:
      - backend
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongodbinventorydata
      ME_CONFIG_MONGODB_ADMINPASSWORD: adgadsfg234GWe5Ggwf34G52fag3
      ME_CONFIG_BASICAUTH_USERNAME: mongobasicauthfw26666
      ME_CONFIG_BASICAUTH_PASSWORD: dasd23GG3321Fa435fuj6c
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_MONGODB_URL: mongodb://mongodbinventorydata:mongo412ddb1r2@mongo:27017/
  traefik:
    image: traefik:v2.3.6
    ports: 
      - 80:80
      - 443:443
    networks:
      - backend
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json

networks:
  backend:
    driver: bridge
    ipam: 
      driver: default 
volumes:
  postgresql_master_data:
  shared_database: 
  cache:
    driver: local



